# Generated by Django 3.1.5 on 2021-01-17 04:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210106_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='11111111111', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
