# Generated by Django 3.1.5 on 2021-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Las Vegas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('NV', 'Nevada')], default='Nevada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='89178', max_length=6),
            preserve_default=False,
        ),
    ]
