# Generated by Django 3.1.5 on 2021-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210117_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_meals',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
