# Generated by Django 3.1.5 on 2021-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('proteins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carbs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
