# Generated by Django 3.1.5 on 2021-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20210110_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='picture_url',
            new_name='large_picture_url',
        ),
        migrations.AddField(
            model_name='meal',
            name='small_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
