# Generated by Django 3.1.5 on 2021-01-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210114_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='menu_sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
