# Generated by Django 3.1.5 on 2021-01-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_menu_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='menu_sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
