# Generated by Django 3.1.5 on 2021-01-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210123_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='small_picture_url',
        ),
    ]
