# Generated by Django 3.1.5 on 2021-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_remove_meal_small_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='on_last_weeks_menu',
            field=models.BooleanField(default=False),
        ),
    ]
