# Generated by Django 3.1.5 on 2021-01-11 03:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20210110_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderitems', '0004_orderitem_is_on_current_menu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'item')},
        ),
    ]
